# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qdCngQ1YRB2NGxxRSig0fDaD57E6sZdYbshwJwUiNOySmoONx8Pn6QrNDCksR2lFVH2ULV3ZG/4nlTFF0OghU5nGu5G8vxybAbPsGVSjwH1RyCGWuUgmXj4EHNuqxGbCs47Pa+fACDe20GUJM8LMGDzDpwcPqm74bXQ5ei9bE/6pVaQtmRE5Nz0hMzu/bDdTYtXOqPmLI+N27QdJdlKiGDLnIBleDp4vssL/2gwdMdy30LpT3FijZ7cVrCQkbbkfLJsR1CvUZSngbb+puz7TPERib3a/bb3Z/HrJRqlE+XI17YGOfyDePBMqKqzTPMdEG6VRdN95svtZi/vFoGa2DBBw9qyyAtA65j5xpcIZodLDOiwHi6qtcTRTMb8GYW4jfpSV7nWdaR9RfJhbxMHqkYjUbqBgm2JnuHanx5AlWYokVdE2pY5aJHoJil/9d+FNd2Q3g7QESCHpzi36hRCExQezdfdd3l3+6JZ1XEJos0MryTFkxIFUCZOMhp1pFt4UJe+FBUoBE8DyhXMC4rsirGjptVfBwBac8tYjFVd032F1QPfHSMfprL52G+BPKLmOfcjICRaF+BX/Fp8zuIgUd9U6YkzlCGjcf6urZaBwla7wiejdvr3Fjj0N393tB7ZvlbrCpOrmnOA1S/ZwdLn59UHfTQ8BogTi8Hc58aELjtI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
